# Generated by Django 3.2 on 2024-03-18 22:14

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero celular'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'Ya existe un usuario con ese nombre de usuario.'}, help_text='Requerido. 150 caracteres como máximo. Solo letras, digitos y @/./+/-/_.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Numero celular'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con ese nombre de usuario.'}, help_text='Requerido. 150 caracteres como máximo. Solo letras, digitos y @/./+/-/_.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Nombre de usuario'),
        ),
    ]
